BEGIN TRANSACTION;

CREATE TABLE CREDENTIAL (
  ID         INTEGER NOT NULL,
  "USER"     VARCHAR(50) CHARACTER SET ISO8859_1 NOT NULL,
  "PASSWORD" VARCHAR(1024) CHARACTER SET ISO8859_1);

ALTER TABLE CREDENTIAL ADD CONSTRAINT CREDENTIAL_PK PRIMARY KEY (ID);

CREATE UNIQUE INDEX CREDENTIAL_LOGIN_IX ON CREDENTIAL("USER");

CREATE GENERATOR CREDENTIAL_SQ;

--START-BLOCK;
CREATE TRIGGER CREDENTIAL_TG FOR CREDENTIAL ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  if (NEW.ID is null) then
    NEW.ID = gen_id(CREDENTIAL_SQ, 1);
END;
--END-BLOCK;

COMMIT;